version: '3'
services:
    server:
        image: 192.168.2.2:5000/nodeapp:latest
        ports:
            - 3000:3000
        networks:
            - app_nw
        restart: always
networks:
    app_nw:
