version: '3'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodeapp
        ports:
            - 3000:3000
        networks:
            - app_nw
networks:
    app_nw:
