Vagrant.configure("2") do |config|
    ###Common for all###
    config.vm.box = "file://./artifact/package.box"
    ###VM specific###
    config.vm.define "ops_base" do |d|
      # Jenkins UI
      d.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
      # Portainer UI
      d.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1"
      d.vm.network "private_network", ip: "192.168.2.2"
      d.vm.synced_folder "../compose", "/home/vagrant/docker_resources"
      d.vm.provider "virtualbox" do |v|
        v.name = "OpVM"
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "app_server" do |app|
      app.vm.network "private_network", ip: "192.168.2.3"
      app.vm.provider "virtualbox" do |v|
        v.name = "AppVM"
        v.memory = 512
        v.cpus = 1
      end
    end
  end