Vagrant.configure("2") do |config|
  config.vm.box = "scotch/box"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "./html", "/var/www/public"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
    vb.name = "LAMP"
  end
end
