# Source:
# https://github.com/bcoste/sample-filebeat-docker-logging/blob/master/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  json.keys_under_root: true
  json.message_key: log
  enabled: true
  encoding: utf-8
  document_type: docker
  paths:
    - '/var/lib/docker/containers/*/*.log'
processors:
- decode_json_fields:
    fields: ["log"]
    target: ""
    overwrite_keys: true
- add_docker_metadata: ~
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3
logging.to_files: true
logging.to_syslog: false
