version: '3.7'
services:
  nextcloud-db:
    image: mariadb
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-bot
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.type == statefull
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    networks:
      - statefull-network
  nextcloud:
    image: nextcloud:16.0.5
    ports:
      - 8080:80
    volumes:
      - nextcloud_vol:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-bot
      - MYSQL_HOST=nextcloud-db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.type == statefull
          - node.labels.db == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 120s
    networks: 
      - statefull-network
volumes:
  nextcloud_vol:
  nextcloud_db:
networks: 
  statefull-network:
    external: true
    name: statefull-network