version: '3.2'

volumes:
  jenkins_home:

networks:
  devops_nw:

services:
  jenkins:
    image: devops/custom-jenkins
    build:
      context: .
      dockerfile: jenkins.dockerfile
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./config:/var/jenkins_home/casc_configs
    networks:
      - devops_nw
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false