version: "3.5"

volumes:
  nextcloud_data:
  nextcloud_db:

networks:
  nextcloud_nw:
# A jelszavak generálásához futtassuk a secret-gen.sh fájlt.
# Secret objektumok létrehozása jelszavak tárolására
secrets:
  mysql_pw:
    file: ./mysql_password.txt
  nextcloud_pw:
    file: ./nextcloud_password.txt

services:   
  nextcloud_db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=nextcloudbot
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_pw
    networks:
      - nextcloud_nw
    volumes:
      - nextcloud_db:/var/lib/mysql
    # Fentebb létrehozott secret felhasználása
    secrets:
      - mysql_pw # /run/secrets/mysql_pw fájlként képződik le, fentebb MYSQL_PASSWORD_FILE változót használva fogja kiolvasni a MariaDB a tartalmát
  nextcloud:
    image: nextcloud:19
    depends_on: 
      - nextcloud_db
    ports:
      - 8080:80
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_pw
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextcloudbot
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_pw
      - MYSQL_HOST=nextcloud_db
    networks:
      - nextcloud_nw
    volumes:
      - nextcloud_data:/var/www/html
    secrets:
      - nextcloud_pw
      - mysql_pw