version: "3.5"

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  nextcloud-nw:

secrets:
  mysql-pw:
    file: ./mysql_password.txt
  nextcloud-pw:
    file: ./nextcloud_password.txt

services:   
  nextcloud-db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=nextcloudbot
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-pw
    networks:
      - nextcloud-nw
    volumes:
      - nextcloud-db:/var/lib/mysql
    secrets:
      - mysql-pw
  nextcloud:
    image: nextcloud:19
    ports:
      - 8080:80
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud-pw
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextcloudbot
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-pw
      - MYSQL_HOST=nextcloud-db
    networks:
      - nextcloud-nw
    volumes:
      - nextcloud-data:/var/www/html
    secrets:
      - nextcloud-pw
      - mysql-pw