# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| 
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../ansible", "/opt/ansible"
  config.vm.synced_folder "../kubernetes", "/opt/kubernetes"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "K3s"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/opt/ansible/init.yml"
    ansible.install_mode = :default
  end
end
