Vagrant.configure("2") do |config|
  ###Common for all###
  config.vm.box = "file://./../packer/artifact/package.box"
  
  ###VM specific###
  config.vm.define "ops_base" do |d|
    d.vm.network "private_network", ip: "192.168.2.2"
    d.vm.network "forwarded_port", guest: 5000, host: 5000
    d.vm.network "forwarded_port", guest: 8081, host: 8081
    d.vm.network "forwarded_port", guest: 9000, host: 9000
    d.vm.network "forwarded_port", guest: 8228, host: 8228
    d.vm.provider "virtualbox" do |v|
      v.name = "OpVM"
      v.memory = 4096
      v.cpus = 2
    end
    d.vm.provision "file", source: "./../docker/devopsinfra", destination: "/home/vagrant/docker"
    d.vm.provision "shell", inline: "curl -s https://raw.githubusercontent.com/anchore/anchore-engine/master/docker-compose-dev.yaml -o /home/vagrant/docker/anchore.yaml"
    d.trigger.after [:up, :reload, :provision] do |t|
      t.run_remote = {inline: "docker-compose -f /home/vagrant/docker/jenkins-dc.yaml up -d && docker-compose -f /home/vagrant/docker/registry-dc.yaml up -d && docker-compose -f /home/vagrant/docker/anchore.yaml up -d && docker-compose -f /home/vagrant/docker/sonar-dc.yaml up -d"}
    end
    d.trigger.before [:suspend, :destroy] do |t|
      t.run_remote = {inline: "docker-compose -f /home/vagrant/docker/anchore.yaml down && docker-compose -f /home/vagrant/docker/registry-dc.yaml down &&  docker-compose -f /home/vagrant/docker/sonar-dc.yaml down && docker-compose -f /home/vagrant/docker/jenkins-dc.yaml down"}
    end
  end
  config.vm.define "app_server" do |app|
    app.vm.network "private_network", ip: "192.168.2.3"
    app.vm.provider "virtualbox" do |v|
      v.name = "AppVM"
      v.memory = 1024
      v.cpus = 1
    end
  end

end
