version: '3.2'

volumes:
  jenkins_home:

networks:
  devops_nw:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24    

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.cloudrole == devopsnode
    volumes:
      - jenkins_home:/var/jenkins_home 
    networks:
      - devops_nw