# Source:
# https://downloads.portainer.io/portainer-agent-stack.yml 
version: '3.2'

networks:
  agent_network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24

volumes:
  portainer_data:

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global # Minden VM-en fusson 1 és csak 1 agent konténer
      placement:
        constraints:
          - node.platform.os == linux
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.cloudrole == devopsnode