version: '3.2'

volumes:
  registry_data:

networks:
  devops_nw:
    external:
      name: cicd_devops_nw #Meglévő hálózat neve (Jenkins YAML hozta létre.) Info: jenkins.yml

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.cloudrole == devopsnode
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - devops_nw