Vagrant.configure("2") do |config|
    ###Minden VM-re végrehajtódik###
    config.vm.box = "ubuntu/xenial64"
    # Fájlokat másolunk a VM-ekre. NEM mappa szinkron.
    config.vm.provision "file", source: "../ansible", destination: "/home/vagrant/ansible"
    # Ansible natív futtatása a Vagrant által a létrehozott VM-ekre.
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/home/vagrant/ansible/docker-install.yaml"
        ansible.become = true
    end
    ###VMek egyéni, eltérő beállításai##
    config.vm.define "ops_base" do |d|
      d.vm.network "private_network", ip: "192.168.2.2"
      d.vm.provider "virtualbox" do |v|
        v.name = "OpVM"
        v.memory = 1024
        v.cpus = 2
      end
    end
    config.vm.define "app_server" do |app|
      app.vm.network "private_network", ip: "192.168.2.3"
      app.vm.provider "virtualbox" do |v|
        v.name = "AppVM"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end