---
apiVersion: v1
kind: Service
metadata:
  name: argocd-web-port
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32080
      protocol: TCP