jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  clouds:
  - docker:
      dockerApi:
        dockerHost:
          uri: "tcp://192.168.56.5:2376"
      name: "docker"
      templates:
      - connector:
          jnlp:
            jnlpLauncher:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          dnsHosts:
          - "8.8.8.8"
          dnsString: "8.8.8.8"
          image: "jenkins/jnlp-agent-node"
        instanceCapStr: "10"
        labelString: "nodejs-agent"
        remoteFs: "/home/node"
        retentionStrategy:
          idleMinutes: 1