
jobs:
  - script: >
      pipelineJob('CI') {
        definition {
            cps {
              script("""\
                pipeline{
                  agent {
                      label "nodejs-agent"
                  }
                  stages {
                      stage("Git clone"){
                          steps{
                              git url:"https://github.com/Zsomx/express_example.git"
                          }
                      }
                      stage("NPM install"){
                          steps{
                              sh "npm i"
                          }
                      }
                      stage("Test"){
                          steps{
                              sh 'npm run-script test'
                          }
                      }
                  }
                }""".stripIndent())
              }
         }
      }
  - script: >
      pipelineJob('CD') {
        definition {
            cps {
              script("""\
                    pipeline{
                        agent {
                            label "docker-agent"
                        }
                        stages {
                            stage("Git clone"){
                                steps{
                                    git url:"https://github.com/Zsomx/express_example.git", branch:"szte"
                                }
                            }
                            stage("Docker build"){
                                steps{
                                        sh "docker build -t ${params.imageName} ."
                                }
                            }
                            stage("Docker push"){
                                steps{
                                    sh "docker tag ${params.imageName} 192.168.56.5:5000/${params.imageName}"   
                                    sh "docker push 192.168.56.5:5000/${params.imageName}"
                                }
                            }
                            stage("Docker clean up"){
                                steps{
                                    sh "docker rmi -f ${params.imageName} 192.168.56.5:5000/${params.imageName}"   
                                }
                            }
                        }
                    }""".stripIndent())
              }
         }
      }
  - script: >
      pipelineJob('Deployment') {
        definition {
            cps {
              script("""\
                    pipeline{
                    agent {
                        label "docker-agent"
                    }
                    stages {
                        stage("Git clone"){
                            steps{
                                git url:"https://github.com/Zsomx/express_example.git", branch:"szte"
                            }
                        }
                        stage("Docker deploy"){
                            steps{
                                sh "docker-compose -f Docker-Compose.yml up"
                            }
                        }
                    }
                }""".stripIndent())
              }
         }
      }