version: '3'
services:
  elasticsearch:
    image: "elasticsearch:7.3.2"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - ops_nw
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: "kibana:7.3.2"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - ops_nw
volumes:
  esdata:
networks:
  ops_nw:
      external:
        name: docker_ops_nw