version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    volumes:
      - 'jenkins_vol:/var/jenkins_home'
    networks:
      - ops_nw
volumes:
  jenkins_vol:
networks:
  ops_nw: