version: '3'
services:
  sonar:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - 'sonar_vol:/opt/sonarqube'
    networks:
      - ops_nw
    restart: always
volumes:
  sonar_vol:
networks:
  ops_nw:
    external:
      name: docker_ops_nw