Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provision "file", source: "config/daemon.json", destination: "/home/vagrant/config/daemon.json"
    config.vm.provision "file", source: "config/startup_options.conf", destination: "/home/vagrant/config/startup_options.conf"
    config.vm.provision "file", source: "./ansible", destination: "/home/vagrant/ansible"
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/home/vagrant/ansible/docker-install.yaml"
        ansible.become = true
    end
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/home/vagrant/ansible/docker-compose-install.yaml"
        ansible.become = true
    end
    config.vm.provision "shell", inline: "cp /home/vagrant/config/daemon.json /etc/docker/daemon.json "
    config.vm.provision "shell", inline: "mkdir /etc/systemd/system/docker.service.d && cp /home/vagrant/config/startup_options.conf /etc/systemd/system/docker.service.d/startup_options.conf"
    config.vm.provision "shell", path: "config/docker_service_reload.sh"
    config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.56.5"
    config.vm.synced_folder "../docker", "/home/vagrant/docker_resources"
    config.vm.provision "shell", inline: "docker compose -f /home/vagrant/docker_resources/jenkins.yml up -d"
    config.vm.provision "shell", inline: "docker compose -f /home/vagrant/docker_resources/registry.yml up -d"
    config.vm.hostname = "jenkins"
    config.vm.provider "virtualbox" do |v|
      v.name = "JenkinsVM"
      v.memory = 2048
      v.cpus = 2
    end
  end