---
- hosts: all
  connection: local
  become: yes
  vars:
    user_name: vagrant
  tasks:
    - name: Delete old Docker runtimes
      apt:
        name: "{{ pkgs }}"
        state: absent
        purge: yes
      vars:
        pkgs:
          - docker
          - docker-engine
          - docker.io
          - containerd 
          - runc
    - name: Install requirements
      apt:
        name: "{{ pkgs }}"
        state: latest
        update_cache: yes
      vars:
        pkgs:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository 
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
        update_cache: yes
    - name: Install Docker
      apt:
        name: "{{ pkgs }}"
        state: latest
      vars:
        pkgs:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Create docker group for sudoless usage
      group:
        name: docker
        state: present
    - name: Add user to docker group
      user:
        name: "{{ user_name }}"
        group: "{{ user_name }}"
        groups: docker
        append: yes
    - name: Start Docker on boot
      service:
        state: started
        enabled: yes
        name: docker