---
- hosts: 127.0.0.1
  become: yes
  vars:
    user_name: vagrant
  tasks:
    - name: Get Docker-Compose binary
      shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: Add execute permission
      file:
        path: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x
